# Generated by Django 3.0.4 on 2020-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_auto_20200311_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['pokedex_id']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_id',
            field=models.IntegerField(null=True),
        ),
    ]
