# Generated by Django 3.0.4 on 2020-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_auto_20200314_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_order',
            field=models.IntegerField(null=True),
        ),
    ]
