# Generated by Django 3.0.4 on 2020-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_auto_20200314_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_url',
            field=models.CharField(blank=True, default='https://tinyurl.com/yx6v48ln', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
